### PR TITLE
feat: added the deployment diagram

### PR DESCRIPTION
**Pull request by Berkmann18**
I'm not 100% sure if it's accurate enough as far as the app's deployment node goes but at least this will give enough indication about how each containers fit together from a deployment/infrastructure perspective.

### CODE REVIEW

**Comment by gr2m** [comment]
is there a rendered graphic  for the diagram we should update, too?

**Comment by Berkmann18** [comment]
@gr2m Not anymore since Netlify automatically generates the static site (even on PRs as shown by the `netlify/ac-architecture/deploy-preview` step which leads to https://deploy-preview-4--ac-architecture.netlify.app/#/2%20Deployment/HOME)

**Comment by gr2m** [comment]
I see! I totally missed the website. Maybe we should mention it on top of the README, too?

**Comment by Berkmann18** [comment]
Yeah, good point, it's in the sidebar of the repo but I guess some might go straight to the README.
Feel free to submit a PR on how you see it fitting in the README, if not I'll do it after ~9:30pm UK time.

**Review by gr2m — APPROVED** [review]
# :shipit:

**Pull request merged**
